### ISSUE TITLE
StopIteration error with test_iter_groups test under Python 3.8

### ISSUE THREAD

**Issue by swt2c** [enthought/apptools#115]
I'm seeing the following with Python 3.8 (it probably occurs under Python 3.7 too):

```
======================================================================
ERROR: apptools.io.h5.tests.test_file.test_iter_groups
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tables/misc/proxydict.py", line 62, in itervalues
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_apptools/build/apptools/io/h5/tests/test_file.py", line 429, in test_iter_groups
    assert set(n.name for n in group.iter_groups()) == set(['subgroup'])
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_apptools/build/apptools/io/h5/tests/test_file.py", line 429, in <genexpr>
    assert set(n.name for n in group.iter_groups()) == set(['subgroup'])
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_apptools/build/apptools/io/h5/file.py", line 434, in <genexpr>
    return (_wrap_node(g) for g in self._h5_group._v_groups.itervalues())
RuntimeError: generator raised StopIteration

----------------------------------------------------------------------
Ran 401 tests in 1.491s

FAILED (SKIP=1, errors=1)
```

**Comment by mdickinson** [comment]
Related to [PEP 479](https://www.python.org/dev/peps/pep-0479/), which explains why it's only showing up in 3.8 (and yes, probably 3.7 too).

Looks like the issue is in PyTables: https://github.com/PyTables/PyTables/blob/1e7b14e87507c2392265321fe18b2f1f5920ea7f/tables/misc/proxydict.py#L62

**Comment by mdickinson** [comment]
Opened upstream issue: https://github.com/PyTables/PyTables/issues/784

For this issue, I'd suggest replacing the offending line with an iterator over `_v_groups.keys()` instead. (We could also use `values`, but that would remove the laziness, since `values` appears to be non-lazy for the `proxydict` that PyTables is using here.)

**Comment by mdickinson** [comment]
FTR, the upstream issue is already fixed, so in theory after the next release of PyTables we could go back to the old code. OTOH, the next major release of `apptools` is likely to be Python 3-only, so at that point we shouldn't be using the `iter*` methods at all.
