### ISSUE TITLE
Convert test suite to use unittest

### ISSUE THREAD

**Issue by mdickinson** [enthought/apptools#119]
The test suite is currently based on nose. nose is no longer maintained. There's a successor, `nose2`, but that doesn't pick up all the apptools tests right now. (Out of the box, nose finds 401 tests, while nose2 finds 174. That may be tweakable.)

We should consider converting all the tests to regular unittest testcases (and then users can still choose to use whichever test runner they prefer).

**Comment by aaronayres35** [comment]
As mentioned in #153 (closed as a duplicate), we will also want to use unittest as the test runner in etstool.py

https://github.com/enthought/apptools/blob/5a136f642d6865970497aa3b2f1f176d56841de2/etstool.py#L146-L147
