### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by mdickinson** [enthought/apptools#120]
We no longer need to support Python 2; related code can be dropped.

**Comment by aaronayres35** [comment]
What is the status of this issue?  I'm not sure what else needs to be done to say we have officially dropped python 2 support

**Comment by mdickinson** [comment]
It's looking good; getting rid of `six` was the single biggest thing (done in #230).

Taking a quick look, I spotted a couple of leftovers (but maybe there's still a `sweet_pickle` PR pending?)

- there's still one `from __future__ import print_function` in `apptools/sweet_pickle/tests`
- there's an `if sys.version_info[0] >= 3:` in the `apptools/sweet_pickle/versioned_unpickler.py`

**Comment by mdickinson** [comment]
> but maybe there's still a `sweet_pickle` PR pending?

Ah yes: #199. I'll close this, then.
