### ISSUE TITLE
Document apptools.lru_cache

### ISSUE THREAD

**Issue by corranwebster** [enthought/apptools#135]
The apptools.lru_cache is a comparatively recent addition to the apptools suite.  It provides a traitified version of an LRU cache.  While this is a fairly well-understood concept, it should have at least minimal documentation and examples of use.

**Comment by kitchoi** [comment]
See discussion #91 regarding removing `lru_cache` altogether.

**Comment by rahulporuri** [comment]
Given that we have decided to remove `LRUCache` altogether, there is no need to document it. See issue https://github.com/enthought/apptools/issues/91. closing.
