### ISSUE TITLE
Remove apptools.type_manager?

### ISSUE THREAD

**Issue by corranwebster** [enthought/apptools#136]
The `apptools.type_manager` module has a lot of overlap with the Traits adaptation system since the latter gained the ability to have multiple adapter registries.

It is, however, used by `apptools.naming` which is in turn used by Mayavi, so we can't simply remove.

The correct way forward is probably to investigate whether `apptools.naming` can use Traits adaptation, and whether Mayavi uses the type manager's objects directly via the naming module

**Comment by aaronayres35** [comment]
coverage report for `type_manager`:

<img width="1093" alt="Screen Shot 2020-11-10 at 12 26 25 PM" src="https://user-images.githubusercontent.com/36972686/98718763-79a4ca80-2354-11eb-9763-9c0f1c8a5d2d.png">

<img width="788" alt="Screen Shot 2020-11-10 at 12 58 18 PM" src="https://user-images.githubusercontent.com/36972686/98718768-7b6e8e00-2354-11eb-8e2d-ea46a7f68a34.png">
