### ISSUE TITLE
Apptools naming UI is Wx-only

### ISSUE THREAD

**Issue by corranwebster** [enthought/apptools#138]
It should grow a Qt backend as well, or be converted to use TraitsUI.

**Comment by kitchoi** [comment]
Apptools naming UI mainly uses `pyface.tree.NodeTree`, which isn't implemented for Qt.
```
>>> from pyface.tree.api import NodeTree
>>> NodeTree()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kchoi/Work/ETS/pyface/pyface/base_toolkit.py", line 184, in __init__
NotImplementedError: the qt4 pyface.ui.qt4 backend doesn't implement tree.tree:Tree
```
It seems that the only wx specific code in `apptools.naming.ui` are these lines:
https://github.com/enthought/apptools/blob/141580e91f6aeb1dc3b74a546814c605550fdef9/apptools/naming/ui/naming_tree.py#L62-L65

One option is for pyface to implement the Qt version of `NodeTree` (and possibly `Tree`). Switching to using TraitsUI may requiring rewriting the whole thing in apptools and it may not be the most efficient path to make `apptools.naming.ui` works on Qt.

**Comment by kitchoi** [comment]
Opened https://github.com/enthought/pyface/issues/809

**Comment by kitchoi** [comment]
It also seems that the `apptools.naming.ui.api.explore` function (the only `apptools.naming` thing used in Mayavi) has not been working in wx either...
```
>>> from apptools.naming.ui.api import explore
>>> class A:
...     a= 1
... 
>>> explore(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kchoi/Work/ETS/apptools/apptools/naming/ui/explorer.py", line 33, in explore
    explorer.open()
  File "/Users/kchoi/.edm/envs/apptools-test-3.6/lib/python3.6/site-packages/pyface/i_window.py", line 203, in open
    self._create()
  File "/Users/kchoi/.edm/envs/apptools-test-3.6/lib/python3.6/site-packages/pyface/ui/wx/application_window.py", line 125, in _create
    contents = self._create_contents(self.control)
  File "/Users/kchoi/.edm/envs/apptools-test-3.6/lib/python3.6/site-packages/pyface/split_application_window.py", line 39, in _create_contents
    return self._create_splitter(parent)
  File "/Users/kchoi/.edm/envs/apptools-test-3.6/lib/python3.6/site-packages/pyface/ui/wx/split_widget.py", line 58, in _create_splitter
    lhs = self._create_lhs(splitter)
  File "/Users/kchoi/Work/ETS/apptools/apptools/naming/ui/explorer.py", line 63, in _create_lhs
    return self._create_tree(parent, self.root)
  File "/Users/kchoi/Work/ETS/apptools/apptools/naming/ui/explorer.py", line 77, in _create_tree
    self._tree = tree = NamingTree(parent, root=root)
  File "/Users/kchoi/.edm/envs/apptools-test-3.6/lib/python3.6/site-packages/pyface/ui/wx/tree/tree.py", line 185, in __init__
    self, parent, style=self._get_style()
TypeError: __init__() missing 1 required positional argument: 'wxid'
``` 

https://github.com/enthought/pyface/pull/810 will fix that. But this begs the question whether the tool is still being needed given this fatal error has not been reported.

**Comment by aaronayres35** [comment]
> It also seems that the `apptools.naming.ui.api.explore` function (the only `apptools.naming` thing used in Mayavi) has not been working in wx either...

So it seems the latest mayavi does not work with wxPython 4 at all https://github.com/enthought/mayavi/issues/972
The wx naming UI did previously work.  In this environment things seem to work okay:

```
(mayavi_demo)~/Desktop/mayavi aayres  (master) $ edm list
# Packages in environment 'mayavi_demo'
#  prefix: '/Users/aayres/.edm/envs/mayavi_demo'
appdirs            1.4.3-1     enthought/free
apptools           4.4.0-10    enthought/free
configobj          5.0.6-2     enthought/free
distribute_remove  1.0.0-4     enthought/free
eam                1.1.0-1     enthought/free
eam_mayavi_app     1.0.2-1     enthought/free
enum34             1.1.6-1     enthought/free
envisage           4.7.0-1     enthought/free
libxml2            2.9.4-1     enthought/free
libxslt            1.1.28-7    enthought/free
mayavi             4.5.0-7     enthought/free
mkl                2018.0.3-1  enthought/free
numpy              1.13.3-4    enthought/free
packaging          16.8-2      enthought/free
pyface             6.0.0-1     enthought/free
pygments           2.2.0-1     enthought/free
pyparsing          2.2.0-1     enthought/free
setuptools         38.2.5-1    enthought/free
six                1.10.0-1    enthought/free
traits             4.6.0-1     enthought/free
traitsui           6.0.0-1     enthought/free
vtk                7.0.0-2     enthought/free
wxpython           3.0.2.0-7   enthought/free
```
But this is a bit of an ancient environment in seeing as it is using Python 2.7.

**Comment by corranwebster** [comment]
Not that ancient - TraitsUI/Pyface support for wxPython was Python 2 only until this year.  So if this worked with Pyface/TraitsUI 6 it was probably working until sometime this year.

So first thing is to get the wx backend back to a working state - it is most likely a Python 3/wxPython 4 conversion issue, either here, or in the pyface code.  Don't worry about Qt for this release, I think.

**Comment by aaronayres35** [comment]
> So first thing is to get the wx backend back to a working state - it is most likely a Python 3/wxPython 4 conversion issue, either here, or in the pyface code. Don't worry about Qt for this release, I think.

FWIW, with the fix made in https://github.com/enthought/pyface/pull/810, the UI seems to work for wx (I can run this example https://github.com/enthought/apptools/blob/master/examples/naming/explorer.py on apptools master and use the explore UI)
However, there is a separate issue when trying to run `mayavi2` with wx 4, so that still needs a fix elsewhere (likely pyface).  

From `apptools` perspective though, with that fix, I think the naming wx _UI_ should work.  "work" is a strong word though, the UI can be opened and you can mess with it, but I'm not certain everything underneath it working as expected since some things aren't well tested.  Those are semi-separate issues though.

**Comment by aaronayres35** [comment]
see related comment: https://github.com/enthought/apptools/issues/146#issuecomment-732281279

It had been decided to remove the `naming` ui piece entirely, so this issue can be closed.
