### ISSUE TITLE
Decide fate of apptools.template

### ISSUE THREAD

**Issue by corranwebster** [enthought/apptools#141]
The `apptools.template` package is designed to provide a system for configuring traits classes and instantiating them according to the template.  This is motivated by, for example, allowing a user to create templates to style Chaco plots and then use those style choices when creating the actual plot instances.

The template objects are also designed to help with serialization and deserialization, allowing the configuration of application state to be separated from the data sources when serializaing.

This is potentially a very useful set of functionality, but it may not be worth preserving.

Or, alternatively, apptools is not the place for it, and it really needs to live in Chaco until a wider use for it is found.

**Comment by rkern** [comment]
It's mostly abstraction for abstraction's sake. Lots of code that does very little. Kill it.
