### ISSUE TITLE
Decide fate of apptools.help

### ISSUE THREAD

**Issue by corranwebster** [enthought/apptools#142]
This is a workbench/envisage plugin for contributing links to external documentation and demos.  It uses preferences for pointing to directories which contain documentation and demo code.

It may make sense to keep for applications still using workbench; it may also make sense to create a Tasks version as well.

It may be used by Mayavi, but that is not clear.

**Comment by aaronayres35** [comment]
FWIW:

`apptools.logger` is definitely used in mayavi but I am not seeing any references to `apptools.help` explicitly.  
The EEP also mentions that `help` is used by `logger`, but Im not sure that is still the case.
Searching the codebase for `apptools.help` you find one result in `logger`:
https://github.com/enthought/apptools/blob/75453bde9d249911724775a92ff6af35b1f9dce0/apptools/logger/agent/quality_agent_view.py#L115-L121
but I've seen no other references to `'apptools.help.IHelp'` or `IHelp` in general inside the `apptools.help` subpackage.  After searching github, it seems `IHelp` existed in the old `enthought.help.help_plugin`:
https://github.com/enthought/legacy-VMSClient/blob/0a8e51256fd6ea43f9e65ef8f0c7a25823d6d16a/src/lib/enthought/src/lib/enthought/help/help_plugin.py#L24-L25

**Comment by aaronayres35** [comment]
`help` is entirely untested.  This is the coverage report for `logger`:

<img width="783" alt="Screen Shot 2020-11-10 at 4 35 37 PM" src="https://user-images.githubusercontent.com/36972686/98741724-c5ff0300-2372-11eb-8c68-92875f5ae37f.png">

<img width="790" alt="Screen Shot 2020-11-10 at 4 35 24 PM" src="https://user-images.githubusercontent.com/36972686/98741725-c8615d00-2372-11eb-91c1-f45ec587b0a5.png">

**Comment by kitchoi** [comment]
Offline discussion: `apptools.help` can go.
