### ISSUE TITLE
Use unittest as the test runner instead of nose.

### ISSUE THREAD

**Issue by rahulporuri** [enthought/apptools#153]
https://github.com/enthought/apptools/blob/5a136f642d6865970497aa3b2f1f176d56841de2/etstool.py#L146-L147

At the moment, nose is used as the test runner but nose is unmaintained and we would like to move away from using nose as the test runner. Note that this might need substantial changes in the testsuite.

**Comment by aaronayres35** [comment]
@rahulporuri it seems there is an already open issue #119.  Shall I close one of them?

**Comment by rahulporuri** [comment]
closing as duplicate of #119. can you update #119 regarding the use of unittest as test runner?
