### ISSUE TITLE
Numerous broken links in docs

### ISSUE THREAD

**Issue by aaronayres35** [enthought/apptools#171]
Many of the links in the documentation are broken and clicking them leads to 404 file not found / other errors.  For example, the first few links on this page:
https://github.com/enthought/apptools/blob/master/docs/source/preferences/Preferences.rst

Some of these links are in docs that will be dropped as the corresponding submodule is planned to be removed.  However, any docs that we expect to keep should be updated and have links fixed.

**Comment by rahulporuri** [comment]
@aaronayres35 i think this should be a release blocker.

**Comment by aaronayres35** [comment]
> @aaronayres35 i think this should be a release blocker.

I will work on fixing soon
