### ISSUE TITLE
Should File implement comparison behavior?

### ISSUE THREAD

**Issue by aaronayres35** [enthought/apptools#228]
Issue motivated by this comment: https://github.com/enthought/apptools/pull/227#discussion_r527592043

In PR #227  the `__cmp__` method was removed from the `apptools.io.file.File` class, since it is no longer honored on python 3 anyway.  We could implement the rich comparison methods to try and provide this behavior but it is unclear if it is needed currently.

**Comment by mdickinson** [comment]
Let's close. If no use has emerged in the last few years, there probably isn't one. And it's far from a natural operation.
