### ISSUE TITLE
Question about preferences

### ISSUE THREAD

**Issue by pyhannes** [enthought/apptools#304]
Is it possible that multiple envisage plugins contribute preferences to the same topic?
E.g. Plugin A has a Python section and a Plugin A section, Plugin B has a Python section and a Plugin B section.
The preferences panes in the end should have 3 tabs "Python, Plugin A, Plugin B", whereas in "Python" there is content from Plugin A and B.

**Comment by pyhannes** [comment]
Any update here please? Or should i use other communication channels for questions?

**Comment by rahulporuri** [comment]
@pyhannes this sounds theoretically possible but I don't know of any sharable examples off the top of my head. Were you asking this question because you tried and ran into some issues or was it a theoretical question?

**Comment by pyhannes** [comment]
That's a theoretical question. I didn't find anything in the code how that would be possible so I'm asking you, maybe i overlooked a not documented feature or something.

**Comment by rahulporuri** [comment]
> I didn't find anything in the code how that would be possible so I'm asking you, maybe i overlooked a not documented feature or something.

I'm sorry @pyhannes but I don't know if anything is documented regarding this at the moment.
