### ISSUE TITLE
LogFileHandler does not support encoding

### ISSUE THREAD

**Issue by mechworrior** [enthought/apptools#323]
Currently `LogFileHandler` does not inherit the `encoding` attribute from `RotatingFileHandler`. 
This is required to enable `utf-8` characters in Logs.

**Comment by rahulporuri** [comment]
It will be good to confirm that all of the kwargs accepted by `RotatingFileHandler` are also accepted by the `LogFileHandler` and that they are passed through as necessary.

**Comment by mdickinson** [comment]
This was fixed in #324.
