### ISSUE TITLE
Tests not running cleanly on master.

### ISSUE THREAD

**Issue by corranwebster** [enthought/apptools#44]
PR #41 seems to have broken about 20 tests. Either the tests need to be fixed, or the code.

**Comment by dpinte** [comment]
@corranwebster thanks for the report. I've just found out this is using nosetests and not the unittest discover tools. I'm fixing the issues. PR will come today or tomorrow morning max. We should really have travis-ci on this project

**Comment by mdickinson** [comment]
For extra fun, run the tests with `PYTHONHASHSEED=random`.  That's giving me a few extra failures, now and then.

**Comment by mdickinson** [comment]
Opened a separate issue (#49) for the `PYTHONHASHSEED=random` failures.

**Comment by mdickinson** [comment]
@corranwebster: Okay to close this issue?
