### ISSUE TITLE
permissions recommends namespace packages that don't work

### ISSUE THREAD

**Issue by rkern** [enthought/apptools#58]
`apptools.permissions` in several `_*_default()` methods tries to import a class from an `apptools.permissions.external` package and then defaults to loading the default class from `apptools.permissions` itself. The documentation recommends that you make an `apptools.permissions.external` namespace package with your custom implementations if you want to use them. We haven't supported namespace packages since it was `enthought.permissions`.

We could fix up the `_*_default()` methods and the documentation to recommend the right way to do things. I'm not really sure why such an inflexible-yet-convoluted scheme was put in place at all, but obviously, we aren't using this code. Should we just deprecate it?

http://stackoverflow.com/questions/33126823/python-enthought-apptools-with-merging-namespace/33136515#33136515

**Comment by corranwebster** [comment]
Closing, as `apptools.permissions` has been removed by #175
