### ISSUE TITLE
Consider making traitsui an optional requirement

### ISSUE THREAD

**Issue by jvkersch** [enthought/apptools#70]
Projects that don't use the GUI parts of apptools are still required to install traitsui if they want to have an environment where all the dependencies are met:

```
09:56 $ edm install apptools
Fetching indices for package repositories.... done

The following packages will be installed:

    apptools   4.4.0-4   787     KiB
    configobj  5.0.6-2    70     KiB
    pyface     5.1.0-5     1.5   MiB
    pygments   2.1.3-1     1.73  MiB
    six        1.10.0-1   19     KiB
    traits     4.6.0-1   636     KiB
    traitsui   5.1.0-2     1.5   MiB

Do you want to continue ? [Y/n]:
```

**Comment by corranwebster** [comment]
Agreed in generality. Which part of apptools were you wanting for a headless environment, in particular?

**Comment by jvkersch** [comment]
> Which part of apptools were you wanting for a headless environment, in particular?

The LRUCache.
