### ISSUE TITLE
Remove LRUCache from apptools

### ISSUE THREAD

**Issue by rahulporuri** [enthought/apptools#91]
[Update] A decision has been made to remove `LRUCache` from `apptools`. See comment further down the thread - https://github.com/enthought/apptools/issues/91#issuecomment-722233227

Python 3.x provides lru cache via the functools stdlib package, which is available on Python 2.x as the backported `functools32` package.

I don't know what the differences between the `LRUCache` that `apptools` provides and how it is different from the one from `functools`. I am also not sure who is using `LRUCache` from `apptools`.

Note that if we do choose to remove the module/class, the next release will have to be a major release.

See https://github.com/enthought/apptools/blob/master/apptools/lru_cache/lru_cache.py

**Comment by corranwebster** [comment]
The main difference is that it uses Traits.  It's probably worth a quick audit to see (a) where we are using it and (b) if there is any reason why we can't replace those uses (eg. are we using the traits-iness of the apptools LRUCache in any way).

**Comment by rahulporuri** [comment]
The `LRUCache` is *not* used in the following enthought OSS projects

- traits
- traitsui
- pyface
- envisage
- codetools
- scimath
- qt_binder
- mayavi

**Comment by kitchoi** [comment]
> The main difference is that it uses Traits. It's probably worth a quick audit to see (a) where we are using it and (b) if there is any reason why we can't replace those uses (eg. are we using the traits-iness of the apptools LRUCache in any way).

From another offline discussion related to https://github.com/enthought/apptools/issues/70, the project that was trying to use LRUCache ended up using the LRU cache from cachetools instead.

**Comment by rahulporuri** [comment]
We could not find visible current users for `LRUCache`. The only feature it provides over `LRUCache` from the functools is the fact that it is implemented using traits so we can listen to changes in the cache. But, even in legacy users of `LRUCache`, the feature wasn't used. Finally, this was introduced when `functools` was not part of the standard library.

In the end, it was decided to remove `LRUCache` from `apptools` in its entirety for the upcoming major release (5.0.0).
